### ISSUE TITLE
Make aws profile configurable

### ISSUE THREAD

**Issue by frankbregulla1111** [cllunsford/aws-signing-proxy#18]
Hi,

currently the proxy always uses the default profile in ~/.aws/credentials. It would be good if you could override this with a command line parameter '--profile' as in the aws cli.

Regards
Frank

**Comment by leehambley** [comment]
@ffriedrich you can simply `export AWS_PROFILE` - the underlaying AWS tools should pick that up.

- http://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by cllunsford** [comment]
Agreed, the `AWS_PROFILE` should do the trick.  Closing...
