### ISSUE TITLE
Can't load CSS for Kibana

### ISSUE THREAD

**Issue by hairyhenderson** [cllunsford/aws-signing-proxy#2]
When loading Kibana through the proxy, there are a bunch of 403s. The first of which is for http://localhost:8080/_plugin/kibana/main.css?_b=6103, which yields a JSON object with this error message from AWS:

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/_plugin/kibana/styles/main.css
_b=6103
host:search-my-es-domain-1234567890abcdefghijklmnop.us-east-1.es.amazonaws.com
x-amz-date:20160301T020512Z

host;x-amz-date

0123456789abcdeffedcba98765432100123456789abcdeffedcba9876543210'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160301T020512Z
20160301/us-east-1/es/aws4_request
0123456789abcdeffedcba98765432100123456789abcdeffedcba9876543210'
```

(I've obviously obscured a bunch of stuff here :wink:)

It seems like any URL with a query string gets incorrectly signed.

**Comment by cllunsford** [comment]
Thanks.  I just got the body signing figured out for requests.  I'll take a look at query string issues.

**Comment by cllunsford** [comment]
I just merged a commit to pass the full URL object to the signing process.  Tested with kibana 4.1 against the AWS elasticsearch instance (v1.5.2) successfully.

**Comment by cllunsford** [comment]
I have little memory of this, but based on my last comment and the ensuing silence I am closing this issue.  Will reopen if I see this crop up again the next time I test.

**Comment by hairyhenderson** [comment]
@cllunsford sorry! seems I missed the update. I'll let you know if this breaks again :)
