### ISSUE TITLE
Add Prerequisites for building

### ISSUE THREAD

**Issue by per06a** [cllunsford/aws-signing-proxy#24]
Useful project! To help folks get started you may want to include a #Prerequsites section, mention `docker-ce`, and link to something like this: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

Then `sudo make gobuild` will work fine.

**Comment by cllunsford** [comment]
Added some build notes to the README.  Thanks!
