### ISSUE TITLE
Support IAM roles

### ISSUE THREAD

**Issue by aequitas** [cllunsford/aws-signing-proxy#3]
Currently this app only works when specifying IAM credentials. It would be nice if it would also support IAM roles. 

https://github.com/aws/aws-sdk-go/wiki/configuring-sdk#specifying-credentials

**Comment by cllunsford** [comment]
Great suggestion, I'll take a look.

Note to self:  We currently use `credentials.NewEnvCredentials()` to pickup keys from ENV vars.  This should get replaced with a full credential chain that will include ENV and IAM role.  If the full chain is used by default, this may be as simple as removing the explicit call to NewEnvCredentials().

**Comment by aequitas** [comment]
I thought it would be that simple as well. Tried to implent that for a pull request, but couldn't get it to work. Ending up with a null pointer panic. But I'm not that fluent yet in go and the aws SDK so might be an error on my part.

**Comment by cllunsford** [comment]
This should be closed with #4 now merged.  I will verify myself before closing this issue.

**Comment by aequitas** [comment]
Thanks, we had already switched to a different solution (because of other reason) so I don't think I will verify it in our setup any time soon. But will be sure to have a look again if we need it again.
