### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by alexrudd** [cllunsford/aws-signing-proxy#5]
Hey,

thanks for putting the work into this, was just about to implement the exact same thing when I thought to search for any existing projects.

I've submitted a pull request (#4) to include a credential lookup chain. what I've also done in my own repository is write a Makefile for building a tiny docker image (7MB - compresses to 2MB on docker hub) from the scratch base image.

The Makefile is a bit hacky and uses the official golang image to compile the app so you don't need to have golang setup locally.

(Feel free to take a look at it: https://github.com/AlexRudd/aws-signing-proxy)

Probably not the best approach for everyone and I don't know how compatible it is with other OS besides Ubuntu; but let me know if you'd like me to open a pull request for the Makefile and accompanying Dockerfile.

Thanks,
Alex

**Comment by cllunsford** [comment]
Hi Alex.  Thanks for the contributions!  I like the idea of using scratch to shrink the image down.  Please do submit the PR for the docker build changes.  I will likely adapt them so I can have travis-ci build binaries and the docker image.

**Comment by cllunsford** [comment]
Compressed images on docker hub are down to 3 MB.  Thanks for contributing!
