### ISSUE TITLE
Provide Basic Auth authentication

### ISSUE THREAD

**Issue by yannickoo** [cllunsford/aws-signing-proxy#9]
In order to secure the proxy we would need to define username and password and set a `WWW-Authenticate` header or stick to another HTTP package which allows us to request/parse credentials easily.

**Comment by msh100** [comment]
In general I don't think this project needs that.

If you're after auth, I'd recommend looking at https://github.com/bitly/oauth2_proxy and not exposing this project to the internet.

**Comment by cllunsford** [comment]
I'm inclined to agree and would prefer to keep authentication out of the mix to keep this project simpler.   In past orgs, we've used a simple nginx/apache config to add http basic or digest authentication to services where required.  I'm closing this for now, but thanks for the feedback!

**Comment by yannickoo** [comment]
Yeah we did the same and I totally agree on that 👍
